import type { HostnameConfig } from "../types";

export const devItems: { [key: string]: HostnameConfig } = {
  "google.com": { enabled: [] },
  "wikipedia.org": { enabled: [] },
  "en.wikipedia.org": { enabled: [] },
  "aa.wikipedia.org": { enabled: [] },
  "ab.wikipedia.org": { enabled: [] },
  "ac.wikipedia.org": { enabled: [] },
  "ad.wikipedia.org": { enabled: [] },
  "ae.wikipedia.org": { enabled: [] },
  "af.wikipedia.org": { enabled: [] },
  "ag.wikipedia.org": { enabled: [] },
  "ah.wikipedia.org": { enabled: [] },
  "ai.wikipedia.org": { enabled: [] },
  "aj.wikipedia.org": { enabled: [] },
  "ak.wikipedia.org": { enabled: [] },
  "al.wikipedia.org": { enabled: [] },
  "am.wikipedia.org": { enabled: [] },
  "an.wikipedia.org": { enabled: [] },
  "ao.wikipedia.org": { enabled: [] },
  "ap.wikipedia.org": { enabled: [] },
  "aq.wikipedia.org": { enabled: [] },
  "ar.wikipedia.org": { enabled: [] },
  "as.wikipedia.org": { enabled: [] },
  "at.wikipedia.org": { enabled: [] },
  "au.wikipedia.org": { enabled: [] },
  "av.wikipedia.org": { enabled: [] },
  "aw.wikipedia.org": { enabled: [] },
  "ax.wikipedia.org": { enabled: [] },
  "ay.wikipedia.org": { enabled: [] },
  "az.wikipedia.org": { enabled: [] },
  "ba.wikipedia.org": { enabled: [] },
  "bb.wikipedia.org": { enabled: [] },
  "bc.wikipedia.org": { enabled: [] },
  "bd.wikipedia.org": { enabled: [] },
  "be.wikipedia.org": { enabled: [] },
  "bf.wikipedia.org": { enabled: [] },
  "bg.wikipedia.org": { enabled: [] },
};
